server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 111111
    key-store-type: PKCS12
    key-alias: zangnangam

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog
    username: root
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwtSecret: MorgothIsMelchor
  jwtExpirationInMs: 6048000
